### ISSUE TITLE
Help me with a custom hook - Formik y Yup - please

### ISSUE THREAD

**Issue by joserangel25** [olaishola05/formik-demo#1]
Hi mr. Ishola.
I have a question. I am using both libraries but I would like to create a custom hook and pass the initialValues, validation and submit as parameters. But Typescript complains because I'm not setting initialValues and validation to the correct types. Could you please show a small implementation of this hook and how to type it?

**Comment by olaishola05** [comment]
Hi @joserangel25 
Do you mind sharing your implementation of the hook? So I can know how to help.

**Comment by olaishola05** [comment]
Hey @joserangel25, Sorry, I got the notification yesterday but was so busy that I couldn't check your solution. However, your implementation was fine; only a few tweaks were required for it to work flawlessly.

- The ObjectSchema type from the Yup library expects between 1 and 4 type arguments, but you may not have provided all the required type arguments, so I used a generic type T that extended the `FormikValues` and passed the T as an argument to the `objectSchema`.
- The second error came from the way you typed Submit; you did not type it to take in a value, which is the form value.

See solution below, I hope it solves the issues you're facing

```
export { useForm }; } from "formik";
import { ObjectSchema} from "yup";

type Submit = (values: FormikValues) => void;

function useForm<T extends FormikValues>(
  initialValues: T,
  validation: ObjectSchema<T>,
  onSubmit: Submit
) {
  const formik = useFormik({
    initialValues,
    validationSchema: validation,
    onSubmit
  });
  return { formik };
}

export { useForm };
```

**Comment by joserangel25** [comment]
Oh, thank you very much mr. @olaishola05. It was very helpful. It's great to know that the fixes were minimal.

Now I will be able to implement it in the project I am doing. Thank you very much again and have a great day!
